registerUser:
    pattern:  /user/register
    defaults: { _controller: UserGeneralBundle:Default:registerUser }

getUser:
    pattern:  /user/{uid}
    defaults: { _controller: UserGeneralBundle:Default:getUser }

getBalance:
    pattern:  /user/{uid}/balance/set
    defaults: { _controller: UserGeneralBundle:Default:changeBalance }

getLastVisit:
    pattern:  /user/{uid}/last_visit
    defaults: { _controller: UserGeneralBundle:Default:getLastVisit }

# BONUS

bonusGetLastVisit:
    pattern:  /user/{uid}/bonus/last_visit
    defaults: { _controller: UserGeneralBundle:Default:getBonusLastVisit }

bonusUpdateLastVisit:
    pattern:  /user/{uid}/bonus/last_visit/update
    defaults: { _controller: UserGeneralBundle:Default:updateBonusLastVisit }
