parameters:
#    user_general.example.class: User\GeneralBundle\Example

services:
#    user_general.example:
#        class: %user_general.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
